<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE language [
        <!ELEMENT language ANY>
        <!ELEMENT locale ANY>
        <!ELEMENT text (source,output)>
        <!ELEMENT source ANY>
        <!ELEMENT output ANY>
        <!ATTLIST language
                src       CDATA    #REQUIRED
                output    CDATA    #REQUIRED
                name      CDATA    #REQUIRED
                native    CDATA    #REQUIRED
                >
        <!ATTLIST locale
                region    CDATA    #REQUIRED
                name      CDATA    #REQUIRED
                native    CDATA    #REQUIRED
                >
        ]>
<language src="en" output="fr" name="French" native="Française">
    <locale region="FR" name="France" native="France">
        <text>
            <source>Feed &amp; Page Settings</source>
            <output>Flux et Paramètres de la page</output>
        </text>
        <text>
            <source>Feed Type</source>
            <output>Type d'alimentation</output>
        </text>
        <text>
            <source>Feed Limit</source>
            <output>Limite d'alimentation</output>
        </text>
        <text>
            <source>Open Authoring</source>
            <output>Ouvrir Authoring</output>
        </text>
        <text>
            <source>In-Content Editing</source>
            <output>En-Content Edition</output>
        </text>
        <text>
            <source>Recent Content</source>
            <output>Contenu Récent</output>
        </text>
        <text>
            <source>Content</source>
            <output>Teneur</output>
        </text>
        <text>
            <source>Content Types</source>
            <output>Types de Contenu</output>
        </text>
        <text>
            <source>Navigation</source>
            <output>Navigation</output>
        </text>
        <text>
            <source>Templates</source>
            <output>Modèles</output>
        </text>
        <text>
            <source>Categories</source>
            <output>Catégories</output>
        </text>
        <text>
            <source>Publish</source>
            <output>Publier</output>
        </text>
        <text>
            <source>Published</source>
            <output>Publié</output>
        </text>
        <text>
            <source>Draft</source>
            <output>Avant-Projet</output>
        </text>
        <text>
            <source>Unpublish</source>
            <output>Dépublier</output>
        </text>
        <text>
            <source>Unpublished</source>
            <output>Inédit</output>
        </text>
        <text>
            <source>Start Date</source>
            <output>Date de début</output>
        </text>
        <text>
            <source>End Date</source>
            <output>Date de fin</output>
        </text>
        <text>
            <source>Batch</source>
            <output>Lot</output>
        </text>
        <text>
            <source>Migrate</source>
            <output>Émigrer</output>
        </text>
        <text>
            <source>MIGRATE</source>
            <output>MIGRATION</output>
        </text>
        <text>
            <source>Parent</source>
            <output>Mère</output>
        </text>
        <text>
            <source>Template</source>
            <output>Modèle</output>
        </text>
        <text>
            <source>Category</source>
            <output>Catégorie</output>
        </text>
        <text>
            <source>Include in Feed</source>
            <output>Inclure dans l'alimentation</output>
        </text>
        <text>
            <source>There is currently no content under the %1 content type.</source>
            <output>Il n'existe actuellement aucun contenu sous le type de contenu %1.</output>
        </text>
        <text>
            <source>You can add new content %1here%2 or add a new content type %3here%4.</source>
            <output>Vous pouvez ajouter du nouveau contenu %1ici%2 ou ajouter un nouveau type de contenu %3ici%4.</output>
        </text>
        <text>
            <source>Archive of Multiple Files</source>
            <output>Archive de plusieurs fichiers</output>
        </text>
        <text>
            <source>Top Node</source>
            <output>Top Noeud</output>
        </text>
        <text>
            <source>ID</source>
            <output>ID</output>
        </text>
        <text>
            <source>Class</source>
            <output>Classe</output>
        </text>
        <text>
            <source>Attributes</source>
            <output>Attributs</output>
        </text>
        <text>
            <source>Parent Node</source>
            <output>Parent Node</output>
        </text>
        <text>
            <source>Child Node</source>
            <output>Noeud de l'enfant</output>
        </text>
        <text>
            <source>"On" Class</source>
            <output>Classe "On"</output>
        </text>
        <text>
            <source>"Off" Class</source>
            <output>Classe "Off"</output>
        </text>
        <text>
            <source>Indentation Spaces</source>
            <output>Espaces d'indentation</output>
        </text>
        <text>
            <source>Slug</source>
            <output>Slug</output>
        </text>
        <text>
            <source>Show Total</source>
            <output>Afficher toutes les</output>
        </text>
        <text>
            <source>There are currently no assets. Use the upload form above to add some.</source>
            <output>Il n'y a pas d'actifs. Utilisez le formulaire de téléchargement ci-dessus pour en ajouter.</output>
        </text>
        <text>
            <source>There are currently no categories.</source>
            <output>Il n'y a pas de catégories.</output>
        </text>
        <text>
            <source>There is currently no navigation.</source>
            <output>Il n'y a pas actuellement de navigation.</output>
        </text>
        <text>
            <source>There are currently no templates.</source>
            <output>Il n'y a pas de modèle.</output>
        </text>
        <text>
            <source>There are currently no content types.</source>
            <output>Il n'existe actuellement aucun type de contenu.</output>
        </text>
        <text>
            <source>Caution: This action can possibly overwrite content.</source>
            <output>Attention : Cette action peut éventuellement écraser le contenu.</output>
        </text>
        <text>
            <source>That URI already exists under that parent category.</source>
            <output>C'est URI existe déjà dans cette catégorie parent.</output>
        </text>
        <text>
            <source>Select Content Type</source>
            <output>Sélectionnez le type de contenu</output>
        </text>
        <text>
            <source>The root URI already exists.</source>
            <output>L'URI racine existe déjà.</output>
        </text>
        <text>
            <source>That URI already exists under that parent content.</source>
            <output>C'est URI existe déjà sous ce contenu parent.</output>
        </text>
        <text>
            <source>Generate URI</source>
            <output>Générer URI</output>
        </text>
        <text>
            <source>That content type name already exists. The name must be unique.</source>
            <output>C'est le nom du type de contenu existe déjà. Le nom doit être unique.</output>
        </text>
        <text>
            <source>All Content</source>
            <output>Tout le Contenu</output>
        </text>
        <text>
            <source>URIs Only (pages, etc.)</source>
            <output>Seulement URI ( pages , etc )</output>
        </text>
        <text>
            <source>Files Only (media, etc.)</source>
            <output>Seuls les Fichiers ( médias , etc )</output>
        </text>
        <text>
            <source>The sites cannot be the same.</source>
            <output>Les sites ne peuvent pas être les mêmes.</output>
        </text>
        <text>
            <source>That navigation name already exists.</source>
            <output>Ce nom de navigation existe déjà.</output>
        </text>
        <text>
            <source>That template name already exists. The name must be unique.</source>
            <output>Ce nom de modèle existe déjà. Le nom doit être unique.</output>
        </text>
        <text>
            <source>That device is already added to that template.</source>
            <output>Ce dispositif est déjà ajouté à ce modèle.</output>
        </text>
        <text>
            <source>URI Type</source>
            <output>Type de URI</output>
        </text>
        <text>
            <source>Images</source>
            <output>Images</output>
        </text>
        <text>
            <source>URIs &amp; Files</source>
            <output>URI et des fichiers</output>
        </text>
        <text>
            <source>All Categories</source>
            <output>Toutes les Catégories</output>
        </text>
        <text>
            <source>All Navigation</source>
            <output>Tout Navigation</output>
        </text>
        <text>
            <source>Trash</source>
            <output>Déchets</output>
        </text>
        <text>
            <source>Scheduled</source>
            <output>Prévu</output>
        </text>
        <text>
            <source>Expired</source>
            <output>Expiré</output>
        </text>
        <text>
            <source>Filter By</source>
            <output>Filtrer Par</output>
        </text>
    </locale>
</language>